/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/arkadiuszklapa/Desktop/dev/r3f/public/tools/Cage-TAqDCvxcxd.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cage(props) {
  const { nodes, materials } = useGLTF('../../public/tools/Cage-TAqDCvxcxd.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={50}>
        <mesh geometry={nodes.torture_device_013_1.geometry} material={materials.DarkMetal} />
        <mesh geometry={nodes.torture_device_013_2.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/tools/Cage-TAqDCvxcxd.glb')
