/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/arkadiuszklapa/Desktop/dev/r3f/public/tools/Torture Device-XVLSpgpSLd.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Torture(props) {
  const { nodes, materials } = useGLTF('../../public/tools/Torture Device-XVLSpgpSLd.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={75}>
        <mesh geometry={nodes.torture_device_015_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.torture_device_015_2.geometry} material={materials.DarkMetal} />
        <mesh geometry={nodes.torture_device_015_3.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/tools/Torture Device-XVLSpgpSLd.glb')
